apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kubectl:
    manifests:
      - config/k8s/*.yaml
build:
  artifacts:
    - image: ticketingregistry.azurecr.io/ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ticketingregistry.azurecr.io/ticketing/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.js'
    - image: ticketingregistry.azurecr.io/ticketing/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ticketingregistry.azurecr.io/ticketing/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ticketingregistry.azurecr.io/ticketing/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ticketingregistry.azurecr.io/ticketing/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'