apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
  labels:
    app: expiration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: sudipmondaldemo.azurecr.io/ticketing/expiration
          env:
            - name: NATS_URL
              value: nats://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-srv

