name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: ticketingregistry.azurecr.io
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
      - name: Build and push image
        run: |
          docker build -t ticketingregistry.azurecr.io/ticketing/auth ./auth
          docker push ticketingregistry.azurecr.io/ticketing/auth
