name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: ticketingregistry.azurecr.io
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
      - name: Build and push image
        run: |
          cd auth && docker build -t ticketingregistry.azurecr.io/ticketing/auth .
          docker push ticketingregistry.azurecr.io/ticketing/auth
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'AzureStack'
      - name: Set up kubelogin for non-interactive login
        run: |
          curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.9/kubelogin-linux-amd64.zip
          sudo unzip -j kubelogin-linux-amd64.zip -d /usr/local/bin
          rm -f kubelogin-linux-amd64.zip
          kubelogin --version
          az config set extension.use_dynamic_install=yes_without_prompt
      - name: AKS Context Set
        uses: azure/aks-set-context@v2
        with:
          resource-group: 'SudipMondal'
          cluster-name: 'ticketing'
          admin: 'false'
          use-kubelogin: 'true'
      - name: Restart kubernetes deployment
        run: kubectl rollout restart deployment auth-depl
