name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: ticketingregistry.azurecr.io
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
      - name: Build and push image
        run: |
          cd auth && docker build -t ticketingregistry.azurecr.io/ticketing/auth .
          docker push ticketingregistry.azurecr.io/ticketing/auth
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'AzureStack'
      - name: AKS Context Set
        uses: azure/aks-set-context@v2
        with:
          resource-group: 'SudipMondal'
          cluster-name: 'ticketing'
      - name: Restart kubernetes deployment
        run: kubectl rollout restart deployment auth-depl
