name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'config/k8s/**'
      - 'config/k8s-prod/**'
env:
  REGISTRY_NAME: ticketingregistry
  CLUSTER_NAME: ticketing
  CLUSTER_RESOURCE_GROUP: SudipMondal 
  NAMESPACE: default
  SECRET: ticketing
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      - uses: azure/k8s-create-secret@v4
        with:
          container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
          arguments: --force true
      - run: |
          kubectl apply -f ./config/k8s
          kubectl apply -f ./config/k8s-prod
