name: tests-auth
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - auth/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3.2.0
      - run: cd auth && npm i && npm run test:ci
      
