name: tests-orders
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - orders/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3.2.0
      - run: cd orders && npm i && npm run test:ci
      
